### ISSUE TITLE
Use middleware for the auth flow?

### ISSUE THREAD

**Issue by eric-burel** [baulml/nextjs-cron#1]
Hi, awesome documentation!
I think to scale up the number of cron jobs, it might be easier to combine a middleware + a folder structure like so:
- `pages/api/crons/_middleware.ts` and do the check from there. 

Middleware are supposedly faster when it comes to minor upfront operations, as they run with a v8 engine instead of a full-fledged Node, they should be more suited for this kind of access validation (when your app goes bigger, you'll probably want to also filter out some IPs etc. to secure it even more).

**Comment by eigenpaul** [comment]
Hi Eric, you're probably right when it comes to the performance and security aspects. I originally implemented this out of sheer necessity and did not really account for faster execution or scalability.
I don't have the time right now but if you want, you can open up a pull request with your suggested changes. I would be more than happy to welcome your improvements to this repo.

Cheers

**Comment by eric-burel** [comment]
Yep I'll try to when the code is more mature. I'll close the ticket in the meantime but at least that may help googlers.

It's not tested yet but here is the middleware:
```ts
/**
 * @see https://github.com/paulphys/nextjs-cron
 * @see https://github.com/vercel/examples/blob/main/edge-functions/basic-auth-password/pages/_middleware.ts
 */
import { NextRequest, NextResponse } from "next/server";

export function middleware(req: NextRequest) {
  const { GITHUB_ACTIONS_APP_KEY } = process.env;
  if (!GITHUB_ACTIONS_APP_KEY) {
    throw new Error(`GITHUB_ACTIONS_APP_KEY not setup, cannot run cron jobs.`);
  }
  const authorization = req.headers.get("authorization");
  if (!authorization)
    throw new Error("No authorization header set when calling cron job.");
  const authorizationSplit = authorization.split(" ");
  if (authorizationSplit.length < 2) {
    throw new Error(
      "Invalid authorization string, should have form 'Something ABCDEF'"
    );
  }
  const ACTION_KEY = authorizationSplit[1];
  if (ACTION_KEY === GITHUB_ACTIONS_APP_KEY) {
    // Process the POST request
    return new Response("Invalid GitHubAction ACTION_KEY", { status: 401 });
  }
  return NextResponse.next();
}
```
with a structure like this:
![image](https://user-images.githubusercontent.com/7983005/160171347-746e7ddf-07c7-422b-ac9a-6f62b0b7d7d2.png)
